[versions]
agp = "8.5.1"
kotlin = "2.0.20"
composeBom = "2024.04.01"
comGithubTakusembaSpotlight = "2.0.5"

[libraries]
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding" }
com-github-takusemba-spotlight = { module = "com.github.takusemba:spotlight", version.ref = "comGithubTakusembaSpotlight" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

